spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    usarname: postgres
    url: jdbc:postgresql://
    password: senha
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${port:8080}